# Generated by Django 4.2.16 on 2024-12-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categories_tags_rename_date_article_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.categories', verbose_name='category_id'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags_id',
            field=models.ManyToManyField(blank=True, to='catalog.tags', verbose_name='tags_id'),
        ),
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.CharField(default='all', max_length=125, verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='tag',
            field=models.CharField(default='none', max_length=125, verbose_name='tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='updatedAt',
            field=models.DateField(blank=True, null=True, verbose_name='date of updating'),
        ),
    ]
